# Generated by Django 5.0 on 2023-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssettings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="logos",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="logos_title",
        ),
        migrations.AddField(
            model_name="footersettings",
            name="instagram",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Instagram "
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="pinterest",
            field=models.URLField(blank=True, max_length=255, verbose_name="Pinterest"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="twitter",
            field=models.URLField(blank=True, max_length=255, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="copyright_line",
            field=models.CharField(
                blank=True,
                default="© 2024 ZERO POINT. Powered By Creative Concept",
                max_length=255,
                verbose_name="copyright",
            ),
        ),
    ]
