# Generated by Django 5.0 on 2023-12-27 04:19

import wagtail.blocks
import wagtail.fields
import wagtailutils.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body_homepage_header_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [], blank=True, null=True, use_json_field=True
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="header",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "hero_image",
                                    wagtailutils.blocks.ImageChooserBlock(
                                        help_text="Optimal Dimension : 1920x1080",
                                        rendition_rules={
                                            "original": "fill-1920x1080-c0|format-webp",
                                            "original_fallback": "fill-1920x1080-c0",
                                        },
                                        required=True,
                                    ),
                                ),
                                (
                                    "hero_image_for_mobile",
                                    wagtailutils.blocks.ImageChooserBlock(
                                        help_text="Optimal Dimension : max width 450px",
                                        rendition_rules={
                                            "original": "width-450|scale-100|format-webp",
                                            "original_fallback": "width-450|scale-100",
                                        },
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
