# Generated by Django 5.0 on 2023-12-27 05:18

import wagtail.blocks
import wagtail.fields
import wagtail_color_panel.blocks
import wagtailutils.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "card_image_with_title",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "card_images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image_title",
                                                    wagtailutils.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "title_color",
                                                    wagtail_color_panel.blocks.NativeColorBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "card_image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : 800x450",
                                                        rendition_rules={
                                                            "original": "fill-800x450-c0|format-webp",
                                                            "original_fallback": "fill-800x450-c0",
                                                        },
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Max image = 4",
                                        max_num=4,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
