# Generated by Django 5.0 on 2023-12-31 06:29

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtailutils.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_homepage_body"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "repeat_in_subnav",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.",
                        verbose_name="repeat in sub-navigation",
                    ),
                ),
                (
                    "repeated_item_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.",
                        max_length=255,
                        verbose_name="repeated item link text",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "clints_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "text",
                                            wagtailutils.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "logos",
                                            wagtail.blocks.ListBlock(
                                                wagtailutils.blocks.ImageChooserBlock(
                                                    help_text="Optimal Dimension : width-300",
                                                    rendition_rules={
                                                        "original": "width-300|format-webp",
                                                        "original_fallback": "width-300",
                                                    },
                                                    required=False,
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
