# Generated by Django 5.0 on 2023-12-31 06:58

import wagtail.blocks
import wagtail.fields
import wagtailutils.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_basicpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner_with_tile",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "background_image",
                                    wagtailutils.blocks.ImageChooserBlock(
                                        help_text="Optimal Dimension : 1920x1080",
                                        rendition_rules={
                                            "original": "fill-1920x1080-c0|format-webp",
                                            "original_fallback": "fill-1920x1080-c0",
                                        },
                                        required=True,
                                    ),
                                ),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtailutils.blocks.PageChooserBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    default="Read More", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "icon_tiles",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : 800x450",
                                                        rendition_rules={
                                                            "original": "fill-800x450-c0|format-webp",
                                                            "original_fallback": "fill-800x450-c0",
                                                        },
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
