# Generated by Django 5.0 on 2024-01-04 06:23

import wagtail.blocks
import wagtail.fields
import wagtail_color_panel.blocks
import wagtailutils.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_basicpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner_with_tile",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "subtitle",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "background_image",
                                    wagtailutils.blocks.ImageChooserBlock(
                                        help_text="Optimal Dimension : 1920x1080",
                                        rendition_rules={
                                            "original": "fill-1920x1080-c0|format-webp",
                                            "original_fallback": "fill-1920x1080-c0",
                                        },
                                        required=True,
                                    ),
                                ),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtailutils.blocks.PageChooserBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    default="Read More", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "icon_tiles",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : width-300",
                                                        rendition_rules={
                                                            "original": "width-300|format-webp",
                                                            "original_fallback": "width-300",
                                                        },
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "card_image_with_title",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "card_images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image_title",
                                                    wagtailutils.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "title_color",
                                                    wagtail_color_panel.blocks.NativeColorBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "card_image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : width-450",
                                                        rendition_rules={
                                                            "original": "width-450|scale-100|format-webp",
                                                            "original_fallback": "width-450|scale-100",
                                                        },
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_with_cta",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtailutils.blocks.PageChooserBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    default="Read More", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "image1",
                                    wagtailutils.blocks.ImageChooserBlock(
                                        help_text="Optimal Dimension : max width 450px",
                                        rendition_rules={
                                            "original": "width-450|scale-100|format-webp",
                                            "original_fallback": "width-450|scale-100",
                                        },
                                        required=False,
                                    ),
                                ),
                                (
                                    "image2",
                                    wagtailutils.blocks.ImageChooserBlock(
                                        help_text="Optimal Dimension : max width 450px",
                                        rendition_rules={
                                            "original": "width-450|scale-100|format-webp",
                                            "original_fallback": "width-450|scale-100",
                                        },
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "title_an_icon_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "discuss_cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtailutils.blocks.PageChooserBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    default="Read More", required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "social_cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtailutils.blocks.PageChooserBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                max_num=1
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "anchor",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    default="Read More", required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "icons_and_title",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.blocks.ListBlock(
                                                        wagtailutils.blocks.ImageChooserBlock(
                                                            help_text="Optimal Dimension : width-300",
                                                            rendition_rules={
                                                                "original": "width-300|format-webp",
                                                                "original_fallback": "width-300",
                                                            },
                                                            required=False,
                                                        )
                                                    ),
                                                ),
                                                (
                                                    "icon_title",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "zigzag_image_and_content",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "content",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtailutils.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : 710x550",
                                                        rendition_rules={
                                                            "original": "fill-710x550-c0|format-webp",
                                                            "original_fallback": "fill-710x550-c0",
                                                        },
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "highlighted_carousel",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "subtitle",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "carousels",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "logo",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : width-300",
                                                        rendition_rules={
                                                            "original": "width-300|format-webp",
                                                            "original_fallback": "width-300",
                                                        },
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "rating",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("1", "1"),
                                                            ("2", "2"),
                                                            ("3", "3"),
                                                            ("4", "4"),
                                                            ("5", "5"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtailutils.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "reviewer_image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : width-300",
                                                        rendition_rules={
                                                            "original": "width-300|format-webp",
                                                            "original_fallback": "width-300",
                                                        },
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "reviewer_name",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "reviewer_subtitle",
                                                    wagtailutils.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "clints_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "logos",
                                    wagtail.blocks.ListBlock(
                                        wagtailutils.blocks.ImageChooserBlock(
                                            help_text="Optimal Dimension : width-250",
                                            rendition_rules={
                                                "original": "width-250|format-webp",
                                                "original_fallback": "width-250",
                                            },
                                            required=False,
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "title_with_cta_service",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtailutils.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "carousels",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtailutils.blocks.ImageChooserBlock(
                                                        help_text="Optimal Dimension : 290x350",
                                                        rendition_rules={
                                                            "original": "fill-290x350-c0|format-webp",
                                                            "original_fallback": "fill-290x350-c0",
                                                        },
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtailutils.blocks.RichTextBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "cta",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "link",
                                                                wagtail.blocks.StreamBlock(
                                                                    [
                                                                        (
                                                                            "page",
                                                                            wagtailutils.blocks.PageChooserBlock(
                                                                                max_num=1
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "link",
                                                                            wagtail.blocks.URLBlock(
                                                                                max_num=1
                                                                            ),
                                                                        ),
                                                                    ],
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "anchor",
                                                                wagtail.blocks.CharBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "label",
                                                                wagtail.blocks.CharBlock(
                                                                    default="Read More",
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
